# Generated by Django 4.2.3 on 2023-07-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
